server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.116.216.209:3306/xyc-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xuyasang110
    driver-class-name: com.mysql.cj.jdbc.Driver
